### PR TITLE
Fix for Away3D blocking DisplayList interactions

### PR DESCRIPTION
**Pull request by TomByrne**

### CODE REVIEW

**Comment by peteshand** [comment]
Hey @TomByrne 
Just an FYI, you are now a collaborator on openfl/robotlegs, so feel free to work directly on this repo

**Comment by TomByrne** [comment]
Yeah I know.
I just thought it's probably a good idea to have you check off on these
kind of changes in case there's a good reason for how things are.
Thanks anyway.

**Comment by peteshand** [comment]
Fair enough..
Only question i have is will these changes cause issues if you're add/removing layers after initialization?

**Comment by TomByrne** [comment]
There may be some issues, but I think it's better than the original implementation.
Before the change where Layer creation was delayed, adding a new Away3D layer "late" in an app lifecycle would always cover any OpenFL interactivity, as it was just using root.addChild().

Now it should behave a bit better.
The only issue I can see is if you remove/destroy Away3D layers then add new ones, the interactivity layer will get added at a higher depth than it should.
I'm thinking that removing layers is pretty rare though, so I figured it's fine for now.

**Pull request merged**
